apiVersion: v1
kind: Pod
metadata:
  name: pod-sa
  namespace: dev-ns
spec:
  containers:
    - name: kubectl-c
      image: alpine/kubectl:latest
      command: ["/bin/sh", "-c"]
      args: ["while true; do echo 'Pod is running'; sleep 5; done"]
  serviceAccountName: webapp-sa
