apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developers-role
  namespace: development
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "update", "delete"]
